name: CI CD Pipleine for frontend application

on:
 push:
  branches:
    - master
    - feature/**

jobs:
 build:
  runs-on : ubuntu-latest
  env:
     APP_NAME: ${{ github.event.repository.name }}  # Repo name as app name
     BUILD_NO: ${{ github.run_number }} 
  steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Check env
      run: |
        echo "Application : $APP_NAME\n Build no : $BUILD_NO"
    - name: Sonar scan
      run: echo "running sonar scan"
    - name: Build and tag Docker image
      run: echo "Building Docker image"
     
    
  
        
