name: CI CD Pipleine for frontend application

on:
 push:
  branches:
    - master
    - feature/**

jobs:
 build:
  runs-on : ubuntu-latest
  steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Sonar scan
      run: echo "running sonar scan"
    - name: Build and tag Docker image
      run: echo "Building Docker image"
     
    
  
        
